#!/usr/bin/env bash

## a hardcoded function to change commit history
## from my old agency email to my personal email
function ghallweb() {
  git filter-branch --env-filter '
  OLD_EMAIL="bmorse@allwebcafe.com"
  CORRECT_NAME="Brandon Morse"
  CORRECT_EMAIL="brandon@morsecodemedia.com"
  if [ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]
  then
      export GIT_COMMITTER_NAME="$CORRECT_NAME"
      export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
  fi
  if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]
  then
      export GIT_AUTHOR_NAME="$CORRECT_NAME"
      export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
  fi
  ' --tag-name-filter cat -- --branches --tags
}
## after this function you will want to run
## git push --force --tags <remote> 'refs/heads/*'
## replace <remote> with either origin, gh, gl, bb based on what you are doing