#!/usr/bin/env bash

function iso2udrw () {
  if [ $# -eq 0 ]; then
    echo "Missing ISO to convert as argument."
  else
    if [ -f "$1" ] ; then
      pname="$(basename "${1%.*}")"
      hdiutil convert -format UDRW -o "$pname.img" "$1"
    else
      echo "ISO file does not exist"
    fi
  fi
}
