#!/usr/bin/env bash

function make_bootable_usb () {
  echo "this process doesn't show any output before it finished and takes a while to complete, so please be patient."
  dd if="$1" of="$2" bs=1m
}
